config/routes.rb
Helpfrog::Application.routes.draw do

  get '/', to: 'main#index'
  get '/index', to: 'main#index'

  get '/results', to: 'results#show'

  resources :places, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :comments

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :place_categories
  has_many :places, through: :place_categories

  # attr_accessible :name

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :place
  before_create :set_password

  validates :content, presence: true

  # attr_accessible :title, :content, :rating, :password, :place_id

  def set_password
    chars = ('a'..'zz').to_a.concat((0..1000000).to_a).concat(('A'..'ZZ').to_a)
    giant_string = chars.to_a.shuffle.join
    start = rand(500)
    self.password = giant_string[start..start+30]
  end
end

app/models/place.rb
class Place < ActiveRecord::Base
  extend Geocoder::Model::ActiveRecord
  geocoded_by :address
  has_many :comments
  has_many :place_categories
  has_many :categories, through: :place_categories

  # attr_accessible :name, :address, :phone_number, :latitude, :longitude, :description

  validates :name, presence: true
  validates :address, presence: true
  validates :latitude, presence: true, numericality: true
  validates :longitude, presence: true, numericality: true

  before_validation :check_or_assign_lat_longs

  def self.find_places_near(address, filter_categories)
    self.joins(:categories).near(address).where("categories.name IN (?)", filter_categories).limit(30)
  end

  def lat_longs?
    if self.latitude && self.longitude
      true
    else
      false
    end
  end

  def check_or_assign_lat_longs
    unless self.lat_longs?
      self.geocode
      sleep 0.25 # avoid geocode rate limit
    end
  end
end

app/models/place_category.rb
class PlaceCategory < ActiveRecord::Base
  belongs_to :place
  belongs_to :category

  # attr_accessible :place_id, :category_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @places = @category.places
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @places = Place.all
  end

  def show
    @place = Place.find(params[:id])
    @comments = @place.comments
  end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  def show
    if params['address'] == ""
      @address = "14th St. and 3rd Ave., New York, NY"
    else
      @address = params['address']
    end
    if params['filter'] == ""
      filter_categories = Category.all.name
    else
      @filter_categories = params['filter']
    end
    @places = Place.find_places_near(@address, @filter_categories)
    respond_to do |format|
      format.html {} # RESTful conventions take care of rendering this
      format.json {
        render json: custom_json_for(@places)
      }
    end
  end

  private

  def custom_json_for(places)
    lat_longs = []
    places.each do |place|
      lat_longs << [place.latitude, place.longitude, place.name, place.id]
    end
    lat_longs.to_json
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<h2>Categories</h2>

<ul>
<% @categories.each do |category| %>
  <li><%= category.name %></li>
<% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.name.upcase %></h1>

<ul>
<% @places.each do |place| %>
  <li><%= link_to place.name, place_path(place) %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helpfrog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <script src="//use.typekit.net/zxt5oga.js"></script>
  <script>try{Typekit.load();}catch(e){}</script>
</head>
<body class="<%= controller.controller_name %>">
    <div class="title">
      <div class="title__card">
        <h1>
          <%= link_to "Helpfrog", index_path %>
        </h1>
        <h2>NYC Social Service Mapper</h2>
      </div>
    </div>
    <div class="container">
    <%= yield %>

</body>
</html>

app/views/main/_search_form.html.erb
<%= form_tag("/results", method: "get") do %>
  <p><%= label_tag 'address', 'Starting Address or Intersection', class: 'form__text-field__label'  %><%= text_field_tag :address, nil, placeholder: "14th and 3rd, New York, New York" %></p>
  <p><%= label_tag "Please select 1 or more categories:" %></p>
  <div class="form__lines">
  <% Category.all.each do |cat| %>
    <p class="form__line"><input class="form__checkbox graphic --image" id="cat_<%= cat.id %>" type="checkbox" name="filter[]" value="<%= cat.name %>"></input><label class="form__label" for="cat_<%= cat.id %>"><%= cat.name %></label></p>
  <% end %>
</div>
  <%= submit_tag "Search", id: "search-button" %>
<% end %>

app/views/main/index.html.erb
<section class="about">
   <p>The city of New York maintains a <%= link_to "database", "https://nycopendata.socrata.com/", target: "_blank" %> of social service agencies. Until now, there was no simple way for ordinary people to browse, filter, or view them. Helpfrog aims to provide the missing link between the open data portal and regular New Yorkers.</p>
   <p>Just enter an address or intersection, choose one or more categories, and we'll show you a map and list of the nearest resources.</p>
   <p>Helpfrog is an <%= link_to "open source", "https://github.com/luciankahn/helpfrog", target: "_blank" %> app. Built and maintained by <%= link_to "Lucian Kahn", "http://luciankahn.com", target: "_blank" %> and <%= link_to "Miriam Nadler", "http://twitter.com/antimytheme", target: "_blank" %>.</p>
</section>

<section class="form">
<%= render 'search_form' %>
</section>

</div> <!-- end .container -->

<footer>

</footer>

app/views/places/show.html.erb
<div class="places__place">

<h1 class="places__title"><%= @place.name %></h1>

<div class="places__meta">
<div class="places__categories">
<% @place.categories.each do |cat| %>
  <p><%= cat.name %></p>
<% end %>
</div>

<p class="places__meta__item"><%= @place.address %></p>
<p class="places__meta__item"><%= @place.phone_number %></p>
<p class="places__meta__item">Last updated: <%= @place.updated_at.strftime("%m/%d/%Y") %></p>
</div>
<div class="places__description">
  <% if @place.description != nil %>
    <p><%= @place.description %></p>
  <% end %>
</div>

</div>

<div class="places__nav">
  <a href="#" id="previous-results">See Previous Results</a>
  <%= link_to "New Search", index_path %>

</div>

app/views/results/show.html.erb
<section class="results" id="results-page">
  <div class="results__title">
    <h2>Resources for <% @filter_categories.each do |category| %> <%= category %> and <% end %> near <%= @address %></h2>
  </div>
  <div class="results__map" id="map-canvas"></div>
  <div class="results__list">
    <h3>Nearest Places</h3>
    <ol>
      <% @places.each do |place| %>
        <li>
          <%= link_to place.name, place_path(place) %>
          <p><%= place.address %></p>
          <a href="tel:<%= place.phone_number %>"><%= place.phone_number %></a>
          <p>Category: <% place.categories.each do |cat| %>
              <%= link_to cat.name, category_path(cat) %>
            <% end %></p></li>
      <% end %>
    </ol>
  </div>
</section>